name: Update README

on:
  push:
    branches:
      - main
      - helpers

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necesario para que git log tenga historial completo

      - name: Update README with last updated date and commits
        run: |
          # Guardamos contenido nuevo en un archivo temporal
          {
            echo "<!-- AUTO-UPDATE:START -->"
            echo "📅 Última actualización: $(date '+%Y-%m-%d %H:%M:%S')"
            echo ""
            echo "## Últimos commits"
            # Últimos 5 commits con hash, mensaje, autor y fecha
            git log -5 --pretty=format:"- %h %s (👤 %an, %ad)" --date=short
            echo ""
            echo "<!-- AUTO-UPDATE:END -->"
          } > update.txt

          # Reemplazamos el bloque en README.md
          sed -i '/<!-- AUTO-UPDATE:START -->/,/<!-- AUTO-UPDATE:END -->/{
            r update.txt
            d
          }' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Actualización automática del README con fecha y últimos commits" || echo "No hay cambios que commitear"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
